* Storylines
** Feyhammer Migration
In 1476, [[Marod Feyhammer]] and [[Elena Feyhammer]] were en route from Calimport to Murann, in the Amn (Calimport -> Memnon -> Velen -> Murann). They were part of a small trading contingent, with three ships. Early one morning, when they were a week away from Velen, Elena remembers how her father barged into her room, in a seeming frenzy. He tore through her drawers, looking for a brooch he himself had gifted her for her fifteenth birthday; one that would amplify certain abjuration spells. He found it, with nary an explanation, and rushed out to talk to the Captain, [[Santanos Morialdos]]. He convinced the captain to stop the ship, showing him visions of treasure far below the sea, and promising him the world.

On the deck of the 'Prima Victoria', in front of the collected crew, Marod opened a portal, and stepped through. Elena remembers the collected crewmembers worridly clutching their weapons, ready for monsters from the deep to come through; they were nervous, held together only by their faith in their captain and lust for treasure.

For three hours they stood there, getting more and more restless. Santanos was eying the portal warily, almost wishing for it to close so he could continue. And then, it happened. Marod returned, carrying a bag with a crown bejeweled with rubies, fit for any king, and gold coins, minted in a time long past. Elena remembers the backs of the coins as having a crossed sickle and trident, though the pattern on the front eludes her.

For the next hour, Santanos excitedly told the captain and the crewmembers of the place he had found -- an underwater palace, protected from the outside by powerful magic, abandoned yet still filled with treasures. He offered to take several soldiers with him -- winking and claiming that he needed more men to carry the treasures out. However, no matter how much she pleaded, he would not allow Elena to go through, and made sure she was kept away from the portal. And so, one hour later, as the sun shone at its height in the sky, he and six other men, all good combinations of brave, foolhardy, and expendable, ventured back through the portal.

They returned four hours later, all smiles, each with pockets filled with gold and jewels, each carrying a vase or samovar or some other treasure, each a walking fortune, regaling those left on the ship with stories of what they'd seen. One told of a library the size of a small village, with books going up the walls to the height of a fair-sized giant. Another told of a kitchen, with poultry that prepared itself and silverware more gem than metal. Each recollection was greater than the last.

Captain Santanos, not wanting to push his luck and run afoul of the pirates of Nelanther, decided on a single further expedition. Across all three ships, thirty good men were chosen to join Marod. Again, Elena tried to join them, and again she was denied. As the sun was setting, they ventured through the portal. All evening the remainder of the crew waited for them, and all night, and the next day, and the next night. That morning, though, the portal started swirling, belching black ichor that burned whatever it touched, and pulling in everything in its surroundings.

Most of the men evacuated the 'Prima Victoria' as she burned. Those that didn't were incinerated by the fire, ingested by the portal, or consumed by the waves. They watched as the ship sunk, and the portal collapsed on itself. They mourned their comrades, but knew that now was time to leave the area; the smoke was sure to bring on predators, and the crew was in no shape to fight them. So they continued on their journey to Velen and the Amn, richer in gold but nothing else.

One day away from Velen, the crews of the remaining ships, 'The Last Stand' and 'Heart of Iron', received a rude surprise. Strewn all over the two ships were the bodies of the thirty men who had gone into the portal. Marod was nowhere to be seen. They were unintelligible, spewing gibberish, looking miserable and confused. The taxed crew cared for their mates until the ship reached Velen, where they were dropped off on the streets. There's no room at Sea for incapable men.

Elena made it to Murann in one piece, but without her father, and much poorer.

** Lemuria Expedition
*** Negotiation
**** Desired Qualifications
- At least five years of adventuring experience.
- Must be able to handily deal with two goblins.
- Knowledge of the arcane, history, foreign languages, and other similar skills desired.
- Two professional references per applicant. 

**** Insurance
Insured with Calceri Bank. 
- In the event of verified death, 1000gp goes to loved ones.
- In the event of maiming, up to 300gp paid out, to be decided in the Harpers' court.
- If Elena returns, an extra 400gp will go to the hero or their descendants.
- For every additional crew member that returns, an extra 50gp will go to the hero or their descendants. 

**** Base salary
- 100gp up front.
- 200gp or 1% of loot upon return, whichever is higher.
- Bonuses to be handed out at the discretion of the hiring party to incentivize heroism.

*** Summary
- [[Elena Feyhammer]] and [[Himo Liadon]] are collecting a group of adventurers (mercenaries) to go hunting for the lost land of Lemuria!

* Legends
** Lemuria
- Legends speak of an island city to the west of Faerun, in the Trackless Sea, north of Chult and East of Lantan.
- Maps from different years differ with regards to the exact location.
- The city disappeared four hundred years ago, utterly and completely.

* Locations
** Lantan
- Former island nation in the trackless sea
- Used to be populated by gnomes and humans
- Advanced technology
** Lemuria
* PC
* NPC
** From Waterdeep
*** Bayaz
- Lord of Waterdeep
- Level 15 Wizard-Sorcerer
- Patron of [[Elena Feyhammer]].
- Wants to 

*** Marod Feyhammer
- Male human calishite, 77
- Father of [[Elena Feyhammer]]
- Calishite merchant and later aristocrat.
- Later in life, wanted to migrate to the Amn: [[Feyhammer Migration]].
 
*** Elena Feyhammer
- Wanted to be an adventurer, like those in the tales.
- Female human calishite, 46
- Level 7 Sorcerer
- Gift for divination
- Has had worsening magical dreams about her father [[Marod]] for the past 7 months. They point her southwards.
- Approached by [[Bayaz]] 

*** Logen Ninefingers
- Level 7 human Barbarian
- Elena's bodyguard
- Six foot Barbarian, wielding a massive claymore and little else.
- Armored in leather.
- Terse, but if he Elena thinks its safe for him to drink, he opens up.
- From the far North -- exiled after briefly achieving hegemony amoung the tribesmen.
- When raging, can become the Bloody-Nine
- Hired by Elena as she was traveling into Waterdeep -- she saw him massacre bandits along the side of the road.

*** Renault Monsigne
- Halfling Cartographer
- Brought in to resolve discrepancies in the maps by [[Elena Feyhammer]].

*** Reginald Truthseeker
- Bald human male monk
- Legal Witness of Waterdeep
- Will try to force honesty from both Elena and the PCs during negotiations.
- Magical quill will be taking notes during negotiations. Crossing out deletes things.
** From Calimport
*** Santanos Morialdos
- Captain of the Prima Victoria, the ship from which [[Marod Feyhammer]] had first found Lemuria.
- Elderly, wrinkled, with a wry sense of humor, a scar across his right eye, and a peg leg.
 
* Sessions
** Session 0
*** Plan
Finish their character sheets.
Introduce their characters to each other (the players)
Familiarize them with the world and have them ask questions and answer some, like what town are their characters from.
Ask them what they want to get out of the game/campaign
Brainstorm relationships and connects
What is something they (the player) wants to accomplish
What is something their character wants to accomplish
Go over any home rules or just the rules (maybe do a simple fight or something here, non-cannon)
Job Interview
*** Things you know
**** Spread of a plague in the South has 
*** Summary
** Predictions
*** If the 
