* Storylines
** Feyhammer Migration
In 1476, [[Marod Feyhammer]] and [[Elena Feyhammer]] were en route from Calimport to Murann, in the Amn (Calimport -> Memnon -> Velen -> Murann). They were part of a small trading contingent, with three ships. Early one morning, when they were a week away from Velen, Elena remembers how her father barged into her room, in a seeming frenzy. He tore through her drawers, looking for a brooch he himself had gifted her for her fifteenth birthday; one that would amplify certain abjuration spells. He found it, with nary an explanation, and rushed out to talk to the Captain, [[Santanos Morialdos]]. He convinced the captain to stop the ship, showing him visions of treasure far below the sea, and promising him the world.

On the deck of the 'Prima Victoria', in front of the collected crew, Marod opened a portal, and stepped through. Elena remembers the collected crewmembers worridly clutching their weapons, ready for monsters from the deep to come through; they were nervous, held together only by their faith in their captain and lust for treasure.

For three hours they stood there, getting more and more restless. Santanos was eying the portal warily, almost wishing for it to close so he could continue. And then, it happened. Marod returned, carrying a bag with a crown bejeweled with rubies, fit for any king, and gold coins, minted in a time long past. Elena remembers the backs of the coins as having a crossed sickle and trident, though the pattern on the front eludes her.

For the next hour, Santanos excitedly told the captain and the crewmembers of the place he had found -- an underwater palace, protected from the outside by powerful magic, abandoned yet still filled with treasures. He offered to take several soldiers with him -- winking and claiming that he needed more men to carry the treasures out. However, no matter how much she pleaded, he would not allow Elena to go through, and made sure she was kept away from the portal. And so, one hour later, as the sun shone at its height in the sky, he and six other men, all good combinations of brave, foolhardy, and expendable, ventured back through the portal.

They returned four hours later, all smiles, each with pockets filled with gold and jewels, each carrying a vase or samovar or some other treasure, each a walking fortune, regaling those left on the ship with stories of what they'd seen. One told of a library the size of a small village, with books going up the walls to the height of a fair-sized giant. Another told of a kitchen, with poultry that prepared itself and silverware more gem than metal. Each recollection was greater than the last.

Captain Santanos, not wanting to push his luck and run afoul of the pirates of Nelanther, decided on a single further expedition. Across all three ships, thirty good men were chosen to join Marod. Again, Elena tried to join them, and again she was denied. As the sun was setting, they ventured through the portal. All evening the remainder of the crew waited for them, and all night, and the next day, and the next night. That morning, though, the portal started swirling, belching black ichor that burned whatever it touched, and pulling in everything in its surroundings.

Most of the men evacuated the 'Prima Victoria' as she burned. Those that didn't were incinerated by the fire, ingested by the portal, or consumed by the waves. They watched as the ship sunk, and the portal collapsed on itself. They mourned their comrades, but knew that now was time to leave the area; the smoke was sure to bring on predators, and the crew was in no shape to fight them. So they continued on their journey to Velen and the Amn, richer in gold but nothing else.

One day away from Velen, the crews of the remaining ships, 'The Last Stand' and 'Heart of Iron', received a rude surprise. Strewn all over the two ships were the bodies of the thirty men who had gone into the portal. Marod was nowhere to be seen. They were unintelligible, spewing gibberish, looking miserable and confused. The taxed crew cared for their mates until the ship reached Velen, where they were dropped off on the streets. There's no room at Sea for incapable men.

Elena made it to Murann in one piece, but without her father, and much poorer.

** Nico's Character
*** Before the campaign
The basic idea of the campaign so far is that our brave heroes, 'Shadow of the Tower' (liz the Rogue Tabaxi), Valeria Greenleaf (Eleonora the Elf Wizard) and Therapon (Nick the Minotaur Paladin) have been recruited as well-paid mercenaries to join a treasure hunting expedition to the forgotten land of Lemuria, buried beneath the sea off the coast to the west of the Calimshan region. 

They have been hired on this expedition by Elena Feyhammer, the daughter of Marod Feyhammer, your employer twenty years prior. In 1476, [[Marod Feyhammer]] and [[Elena Feyhammer]] were en route from Calimport to Murann, in the Amn (Calimport -> Memnon -> Velen -> Murann). They were part of a small trading contingent, with three ships. You were then a crew member (details up for discussion!) aboard the largest ship of the contingent, the 'Prima Victoria'. 

One day, when you were a week away from the city of Velen, you and the rest of the crew were called on deck, where Captain Santanos told the crew to prepare their weapons, just in case; apparently, your employer, Marod, was convinced that he could open a portal to riches. Seemed risky to you at the time. In front of the collected crew, Marod opened a portal, and stepped through.

For three hours they stood there, getting more and more restless. The captain was eying thwww.reddit.com/r/Bubogleheadsttcoin/comments/85i4yf/im_now_relaxed_a_phd_student_in_economics_proved/e portal warily, and started sending crew members away, giving them what seemed to be busywork. Soon after, Marod returned, carrying a bag with a crown bejeweled with rubies, fit for any king, and gold coins, minted in a time long past (quite dusty, the lot).

For the next hour, Santanos excitedly told the captain and the crewmembers of the place he had found -- an underwater palace, protected from the outside by powerful magic, abandoned yet still filled with treasures. He offered to take several soldiers with him -- winking and claiming that he needed more men to carry the treasures out. You had the good sense to stay back from this offer. And so, one hour later, as the sun shone at its height in the sky, he and six other men, all good combinations of brave, foolhardy, and expendable, ventured back through the portal.

They returned four hours later, all smiles, each with pockets filled with gold and jewels, each carrying a vase or samovar or some other treasure, each a walking fortune, regaling those left on the ship with stories of what they'd seen. One told of a library the size of a small village, with books going up the walls to the height of a fair-sized giant. Another told of a kitchen, with poultry that prepared itself and silverware more gem than metal. Each recollection was grander than the last.

The captain decided on a single further expedition. Across all three ships, thirty good men were chosen to join Marod. You were one of them. As the sun was setting, you ventured through the portal. 

Your exploration:
- There was a glass dome around the palace protecting it from the water and monstrosities of deep. Several tentacles beasties, seeing the illumination of your torches, made an attempt to reach through, but their attempts to reach you were futile.
- The dome seemed spherical, though because of its size you didn't get to explore the whole sphere.
- Marod was pushing for the group to head higher up the palace, claiming that it seemed like that is where the most glamorous treasures should be. With the exception of five men who decided to explore the basement, the crew headed up.
- Everything looked as if it's been untouched for centuries.
- There was opulence here in the past. Artwork decorated the walls (and the floors), depicting humanoids and landscapes, all dusty. Cracked marble tables, golden goblets lying on the floor, and dusty tomes were commonplace.
- There were signs of a struggle having taken place a long time ago -- large gashes in the gold-plated pillars, scattered ancient weaponry and armor, and the occasional magical trinket, quickly appropriated.
- Occasionally, the earth would shake, and a staticy sound, like a crowd cheering far away, could be heard reverberating throughout the complex.
- There were signs that the shaking had been happening for a long time -- fallen chandeliers, bones and weapons and armor littering rooms, with few complete remains to be seen.
- There was green goo along the ceiling in many of the rooms, but it seemed harmless -- it didn't react to anything the sailors did. Then again, none of them were eager to touch it.


You reached a staircase that Marod claimed must lead to the pinnacle of the dome, based on the curvature. It made sense. He collected the crew and everyone ascended the stairs. Ahead was a giant door, maybe fifteen feet tall. It had patterns of tridents and sea turtles and tentacles, engraved in gold. Marod pushed to open it, but it wouldn't budge. You helped him open it. You succeeded.

You remember feeling trapped in your body. Your limbs were moving, carrying you further into the room. The most elaborate yet. But it wasn't dusty. It was occupied. There was a throne, facing towards you, though you don't remember what sat in it. Or maybe you just didn't understand it. There was a small sun, near the curved top of the dome, providing light, though how that could be you couldn't understand. And the dome was completely covered in the green phosphorescent goo, obscuring the ocean. This green goo had eyes, you remember. Thousands of eyes, all irregularly spaced and differently sized, all staring at you.

You and the rest of the crew calmly walked to the middle of the room, standing in a line, facing the figure on the throne. You were halfway along it. Marod stood apart from everyone else. He took out his knife, chanted a few words you couldn't make out, and cut out the heart of the first sailor in line. The sailor gasped, and fell to his knees; seconds later he was standing up again. Marod handed him the heart to eat, which he did, and he stood apart from the rest, facing the rest of the sailors in line, still bleeding from his chest, his face messy and red.

This process was repeated a dozen more times. Half of the crew was now staring at you, still trapped in your own body, unable to move. Marod was turning to face you.

You don't know where the strength came from, but you broke free of the spell, burying your axe in Marod's forehead, laying him low. This seemed to break the spell for everyone else; you and the remaining half of the crew rushed to flee, with the converted men hot on your heels. As you ran down the palace, you saw that the goo everywhere now had eyes, all watching you as you run by. 

You don't know what happened to everyone; what you know is that the portal you went through wasn't functional, so you did the only thing you could think of: run further down. You ran below the palace, finding a giant winding staircase, several hundred feet tall and heading down. This staircase was the first place you've seen with no hell-goo. You make your way down, and emerge into what must've been the city proper. You see that the staircase was inside is a massive tower, the top of which merges with the palace above.

The city is overgrown. It is your new home. 

*** Beginning of campaign
Your new home is dreary. Once, it was a glorious place. From the architectural remains, that much is obvious. As you first walked through it, you could see parks, roads, and buildings all indicitive of a thriving civilization. But all of it was overgrown. It hadn't been maintained in centuries. And you were still being chased, so you had other priorities.

Making your way through the forest-city, you lost your pursuers, and after days of exploration, hunger, and duels with half-plant humanoid monstrosities (delicious, you find), you met the true inhabitants of the city.

They were depressing; pitiful remnants of what civilization was once here, dulled by centuries of inbreeding. They were humanoid, but most seemed to be half-breeds (or thinner). They spoke common, and asked you and the other three survivors from the crew for stories of the outside world. They welcomed you, for you were hope and change, and they had little.

They hold their society together through fear and tradition. They revere a savoir, Josef, now dead, known only through stories from a thousand years ago. They say he established the wards that protect parts of the city from the unholy remnants of the servants of Khalul, the trapped monarch. You don't know if he ever existed, but his wards are real enough. You've seen them at work.

They farm and hunt for food; you found your place. 

At first their treasures bedazzled you; collected from all across the city, the treasures found here could perhaps shame all of modern Waterdeep. But, gold cannot feed a hungry village, and many times have you pondered at how you've changed, that you'd be willing to trade gold for its mass in bread.

After three years of living with the natives, you woke up bound, gagged, and apologetically sacrificed to the soul of the city by being thrown into the abyss under the tower. Then, the next time the portal opens... you open your eyes...

** Lemuria Expedition
*** Negotiation
**** Desired Qualifications
- At least five years of adventuring experience.
- Must be able to handily deal with two goblins.
- Knowledge of the arcane, history, foreign languages, and other similar skills desired.
- Two professional references per applicant.

**** Insurance
Insured with Calceri Bank. 
- In the event of verified death, 1000gp goes to loved ones.
- In the event of maiming, up to 300gp paid out, to be decided in the Harpers' court.
- If Elena returns, an extra 400gp will go to the hero or their descendants.
- For every additional crew member that returns, an extra 50gp will go to the hero or their descendants. 

**** Base salary
- 100gp up front.
- 200gp or 1% of loot upon return, whichever is higher.
- Bonuses to be handed out at the discretion of the hiring party to incentivize heroism.

*** Summary
- [[Elena Feyhammer]] and [[Logen Ninefingers]] are collecting a group of adventurers (mercenaries) to go hunting for the lost land of Lemuria!

* Legends
** Of Lemuria
- Legends speak of an island city to the west of Faerun, in the Trackless Sea, north of Chult and East of Lantan.
- Maps from different years differ with regards to the exact location.
- The city disappeared 400 years ago, utterly and completely.
  
* Locations
** Lantan
- Former island nation in the trackless sea
- Used to be populated by gnomes and humans
- Advanced technology
** Lemuria
** Ashenmire Palace
- Three story palace, one of the largest in the Sea Ward of Waterdeep (the wealthiest ward of the city)
- Circular, with greenery on the edges of the rectangular property.
- Palace itself is deep red, with intricately carved white columns with gold-plated bases  on the outside 
- Strategically positioned globes lit with purple fire.
- Floors can shift locations.
- Circle has a radius of about 150 feet.
*** For the Farewell Feast
- Upon entering the building, big circular open area with high ceilings.
- Lavishly decorated; painted windows (but none on the outside), frescos on the ceiling.
- Bar in the middle of the room, tables arranged around it for the guests.
- Elegantly dressed men and women (mostly women) in red and purple uniforms relax in a lounge to the side, talking to each other. They mostly stop as people come in and start walking around.
- Ashenmire is standing in the corner, wearing a white suit. As the crew comes in, he welcomes them.
- Santiano is playing music in the corner.
** Heart of Iron


* PC
** Shadow of the Tower
** Valeria Greenleaf
- 250 years old
- Merchant of Waterdeep
- Family of merchants
- Operate warehouses, caravans, stores.
- Elf Cosmetics, front
- Emerald Enclave
- 
** Therapon
- Minotaur
* NPCs
** From 'Heart of Iron'
*** Ishri
- Eater of Khalul
- Will try to infiltrate mission, sabotage it, and take the treasures for Khalul
- In true form, is a tall, dark skinned woman. 
- Black eyes.
- Wears black arabic cape with a brooch that shines in the darkness holding her cape on her chest.
*** Captain Monsignore
- Captain of the 'Heart of Iron'.
- Grizzled, but french.
- In the Amnish navy for twenty years.
- Was caught smuggling several hearts of Glustrod as an on-duty captain, but was rescued from execution by a mysterious stranger.
- Used his smuggling wealth to buy a new ship and became a pirate hunter operating in Waterdeep.
- Wears a sea-dragon-skin cape (he killed it himself)
*** Bruce the Beast (Willis)
- First mate
- Five feet tall dwarf male
- Can be freakishly strong when his ship's in danger
- Got his nickname when he singlehandedly shifted the sail on the 'Heart of Iron', turning the ship in a critical moment against 'Barborbossa'.
*** Pudge (Pudgeosopher, po-boy to his friends)
- Ship cook
- Gloriously fat
- Once fought off three pirate scum that entered the kitchen.
*** Helmswoman Anisaf
- Jolly spirit
- Male 90s wood elf
- Not much of a fighter, but a good archer
- Likes steering things
- Close friends with Bruce
*** Arka Bruceaxe
- Dwarf priestess of Lathander

** From Ashenmire Palace


** From Waterdeep
*** Bayaz
- https://vignette.wikia.nocookie.net/firstlaw/images/2/2e/Bayaz-GraphicNovel.jpg/revision/latest?cb=20140307222848
- Bayaz looks maybe sixty, heavily built, with a strong face, deeply lined, and a close-cropped grey beard around his mouth. He is entirely bald, with a tanned pate.
- Goes by 'Lord Colm Ashenmire'.
- Lord of Waterdeep
- Old Timer influences (mostly rules) Waterdeep, used to rule Luskan and the Amn but got lazy.
- Level 15 Wizard-Sorcerer
- Patron of [[Elena Feyhammer]].
*** Yoru Sulfur
- https://vignette.wikia.nocookie.net/firstlaw/images/3/34/YoruSulfur-GraphicNovel.jpg/revision/latest?cb=20140307222306
- Male, human, 30s, southern skin color, but not so dark as to be Calmshite
- One blue eye and one green
- Nondescript dress, pleasant but forgettable, humble manner.
- [[Bayaz]]'s eater and shapeshifter.
*** Khalul
- Trapped by Bayaz in Lemuria.
- Old Timer ruled Calimshan, Lantan from his seat in Lemuria until 400 years ago.
- Released by [[Marod Feyhammer]].
*** Marod Feyhammer
- Male human calishite, 77
- Father of [[Elena Feyhammer]]
- Calishite merchant and later aristocrat.
- Later in life, wanted to migrate to the Amn: [[Feyhammer Migration]].
*** Elena Feyhammer
- https://img00.deviantart.net/499d/i/2013/083/d/b/melisandre_by_imperfectsoul-d5z5nac.jpg
- Wanted to be an adventurer, like those in the tales.
- Female human calishite, 46
- Level 5 Sorcerer
- Gift for divination
- Has had worsening magical dreams about her father [[Marod]] for the past 7 months. They point her southwards.
- Approached by [[Bayaz]]
- Wearing noble clothing (maybe trying a bit too hard)
*** Logen Ninefingers
- https://vignette.wikia.nocookie.net/firstlaw/images/1/19/Logen_ninefingers_wip_y_icedwingsart-d8guxcx.jpg/revision/latest?cb=20150512083852
- Level 7 human Barbarian
- Elena's bodyguard
- Six foot Barbarian, wielding a massive claymore.
- Armored in leather.
- Terse
- Very heavily scarred face and arms.
- From the far North -- fled into exiled after briefly achieving hegemony amoung the tribesmen.
- When raging, can become the Bloody-Nine
- Hired by [[Bayaz]] to accompany [[Elena Feyhammer]].
*** Renault Monet
- Halfling Cartographer
- Brought in to resolve discrepancies in the maps by [[Elena Feyhammer]].

*** Reginald Truthseeker
- Bald human male monk
- Legal Witness of Waterdeep
- Will try to force honesty from both Elena and the PCs during negotiations.
- Magical quill will be taking notes during negotiations. Crossing out deletes things.
** From Calimport
*** Santanos Morialdos
- Captain of the Prima Victoria, the ship from which [[Marod Feyhammer]] had first found Lemuria.
- Elderly, wrinkled, with a wry sense of humor, a scar across his right eye, and a peg leg.
* Artifacts
** Glustrod's Heart
- Named after the first Eater, Glustrod
- Gives the eater of the heart a taste for human flesh.
* Sessions
** Session 0
*** Plan
Finish their character sheets.
Introduce their characters to each other (the players)
Familiarize them with the world and have them ask questions and answer some, like what town are their characters from.
Ask them what they want to get out of the game/campaign
Brainstorm relationships and connects
What is something they (the player) wants to accomplish
What is something their character wants to accomplish
Go over any home rules or just the rules (maybe do a simple fight or something here, non-cannon)
Job Interview
*** Summary
** Session 1
*** Things you know
**** Plague in the south
- The Wasting Hunger
- Calimport has been hit with a devastating plague as of four years ago, and travelers and traders are avoiding all of Calimshan.
- Has spread despite the intervention attempts of several priesthoods.
- The afflicted start wasting away and hungering for humanoid flesh.
- After a couple of days they go mad for it and attack those caring for them. New cases crop up and are put down every day.
- A new cult has risen in the past two years to take advantage, helping the afflicted but gaining political control over the city. Led by Khalul
*** Plan
**** Shopping, preparations for the jouney.
**** Invitation to the ball at Lord Colm Ashenmire's palace
***** Meeting
- The night before the ship is to head out.
- Messenger girl (Allison Bonkers) is a bit late, wants a nice tip because he found you.
***** Yoru Sulfur
 - When the players arrive near the entrance to the grounds, they see another carriage heading towards another entrance. 
 - May hear some screaming from it
 - Horses may seem freaked out. 
 - One passenger and one driver. Driver is a deaf-mute gnome. Passenger is Yoru Sulfur in his normal form. 
 - 'Coffin' with shackled human afflicted with the wasting hunger
 - If followed, will stop shortly before entering the mansion and approach, trying to dissuade from following.
 - Will take coffin through separate entrance to a medical lab.
***** Ball
- Round ball area, decorated lavishly with frescos and painted windows and whatnot.
- Lord Ashenmire is present, avoiding being too social but also invigorating the guests.
- Friendly Guards standing by the doors further into the mansion.
- Entertainers hired; beautiful men and women to go around making dignified, beautiful conversation with the guests.
- Elena, Logen, Monsignore and the rest of the crew are here.
- Pudge the cook is suspiciously sniffing everything before eating it but enjoying himself.
- A small band is playing classical music in the corner.
- Free drinks and rousing speeches!
- Opportunities to talk to people.
- Some start dancing, some with other crew members and other with the entertainers.
- Two of the entertainers stand out; one is a fancy looking jester breathing fire, the other does insane acrobatics, jumping super high and stuff.
**** Rescue on the 'Heart of Iron'
***** Someone will try to get the party to the ship with them
- Maybe [[Captain Monsignore]] will be called away during a conversation with the party in order to deal with how close the expedition will get to Calimshan
- Maybe a sailor will want to show off the ship.
- Maybe a sailor will want to show off the supplies.
- Maybe a sailor will want to show off the power core.
***** Elena and Logen will be under attack
- Corpses leading up to the ship
- Under attack, probably in Elena's room.
****** Ishri Stats
- 90 Health
- Two attacks per turn
- Hits for 2d6 + 2 (9), +7 to hit
******* Spells
- Disguise Self (1)
- Crown of Madness (2)
- Misty Step (2)
- Mirror Image (2)
- Vampiric Touch (3)
- Major Image (3)
- Freedom of Movement (4)
- Detect Thoughts
- Finger of Death? (7)
- Ishri will try to escape if victory in doubt, 
- Elena will communicate with Ashenmire, signal to the crew members that they should get underway before an investigation delays the trip.
**** Hunt for the Eater at sea.
***** Ishri
****** Goals
  - Get onto the Heart of Iron
  - Weaken the expedition without being detected.
  - Wreck the expedition when Lemuria has been found and bring it to the surface for [[Khalul]].
****** Strategies
  - Tries to kill and impersonate Logen. Can throw a hole at a wall and escape if cornered.
  - Will try to kill and impersonate someone else if that fails.
  - Maybe [[Helmswoman Anisaf]], threw her overboard, and assumed her role.
  - The next day, murders another sailor "Dolorous Edd", hides the corpse beneath some wood on floor -2.
  - If close to being cornered, may take a risk and try to kill and impersonate the captain.

***** Yoru Sulfur
****** Goals
  - Get onto the Heart of Iron
  - Remain undetected so as to ensure the loyalty of the crew.
  - Ensure the success of the mission to secure the treasures of Lemuria for [[Bayaz]].
****** Strategies
  - Will try to murder and impersonate any of the crew ("Bruce") to get onto the mission.
  - If a hunt for an eater begins and the ship turns towards land, will temporarily sabotage the power core to prevent other eater escape.
  - Will assume that the captain is an obvious target.
  - 

** Predictions
*** If the 

* Stuff
** Crown of Vesuvius
- Attunes the wearer to the volcanic elements, earth and fire, and allows telepathy and bargaining with the elemental kings of the world. They are driven to desire it.
- Intricate crown made of gold, bejewled with rubies, including a huuuge one on the front.



* tables

| d20 | WEIRD THING FOUND:                                                                                                                                                                                                                                                                                           |
|   1 | Stalactite (or other handy ceiling structure) is actually hermit crab-like creature waiting to crush and eat the next thing that walks under it. Falling damage + paralyzing poison attack.                                                                                                                  |
|   2 | Everyone loses their voices while in this corridor. Roll on wandering monster table—while in the corridor, players must fight the monster without saying anything (other than describing attacks to the GM). Hand motions, movements, etc., must be mimed, not described.                                    |
|   3 | Walking through the next exit takes you through the exact same place you entered the room/hallway from originally. Appears to be a space-time hiccup that only happens once.                                                                                                                                 |
|   4 | There’s a holy relic of a now-defunct religion on the floor.                                                                                                                                                                                                                                                 |
|   5 | Any shadows cast on the wall are not obviously of the objects casting them.                                                                                                                                                                                                                                  |
|   6 | Roll on wandering monster table of choice. That’s the moster currently taking a leak in the corner. If multiple, they’re “sword fighting”. Surprise round!                                                                                                                                                   |
|   7 | Natural gas reservoir behind one of the walls (sounds hollow if checked). If the wall is breached, an odorless, colorless, flammable, heavier than air, suffocating gas begins filling up room.                                                                                                              |
|   8 | Wall has writing on it (“Gorgy wuz here”) and crude line drawings that look like orc penises.                                                                                                                                                                                                                |
|   9 | The corridor reeks. Anyone staying it in for longer than their CON in minutes will probably end up throwing up.                                                                                                                                                                                              |
|  10 | Corridor narrows to a point that it must be crawled through on knees and elbows for approximately 10 feet. Claustrophobia, loot not fitting through, and getting stuck are all possibilities.                                                                                                                |
|  11 | Careful examination of the water in this area reveals that it travels just slightly uphill.                                                                                                                                                                                                                  |
|  12 | While the corridor doesn’t seem to have any bends, the exit is not viewable from the entrance and vice versa.                                                                                                                                                                                                |
|  13 | When the adventurers enter the corridor, they hear the dying gasp of a man. As they continue down, the clash and clang of sword on sword echos through the room. Upon reaching the end, there is the sound of two swords being unsheathed. And as the last adventurer exits, they hear a man whisper, “Now!” |
|  14 | While the walls look like rough stone, they feel glassy smooth to the touch.                                                                                                                                                                                                                                 |
|  15 | Floor is so slippery that only the most careful, dextrous, or lucky of folks will get through without slipping and falling (save or fall every 10 ft). Makes quite a racket, and each fall costs 1d4 of HP (if anyone goes to 0HP due to this, treat as a broken limb).                                      |
|  16 | The surfaces and air are uncomfortably hot and smell of brimstone.                                                                                                                                                                                                                                           |
|  17 | The walls and ceiling creak, groan, and hum.                                                                                                                                                                                                                                                                 |
|  18 | A puff of wind blows the torch out. A lamp fades and self-extinguishes. No flint will strike. This room refuses to be illuminated by any non-magical means. Luckily, someone saw the exit right before that happened, but they’ll have to navigate in the dark.                                              |
|  19 | The original entrance has experienced a bit of a cave-in. Will take 1d6 hours to excavate.                                                                                                                                                                                                                   |
|  20 | Mushrooms dot the walls. Regular old edible mushrooms. Of course, don’t tell your players that.                                                                                                                                                                                                              |


* Encounters
** Edward's Lab
*** Statuses
- Ooze poisoning: -3 intelligence, disadvantage on all saving throws, 3 damage per turn, may be cleansed/uncursed.

*** Creeps
**** Edward Malpin
  - 60 HP
  - 2 attacks/round
  - Drink Potion - Drink any potion color
  - Throw Potion - Throw any potion color
  - Control Zombies: Concentration - Zombies act coordinated and intelligently.
  - Prod Zombies: An extra zombie comes out

**** Ooze Zombies
  - 3 Ooze Zombies
  - +1/turn 
  - 25 HP
  - +5 hit
  - 7-9 damage ooze poisoning on save below 13
  
*** Potions drink/throw
**** Yellow:
 - 1 Potion of Shield: 40HP Shield / Remove all shields
 - 2 Potion of Speed: +2 AC, advantage on Dex, extra action each turn for 3 turns. / For next two turns, if fail dex save, skip turn
 - 3 Potion of Invisibility Target invisible / same
 - 4 Potion of blight: Ingested: DC18 CON. On fail, 4d6 necrotic, half on save. Thrown: Target takes 4d6, all creatures adjacent make DC15 DEX save. On fail full damage, on save half.

**** Blue:
 - 1 Potion of Stone form: Target turned into heavy stone for one turn. Constitution save. / same
 - 2 Potion of Remove Curse: Remove curse from target / same
 - 3 Potion of Fire Dowsing: Water
 - 4 Potion of Shrinking: Target size goes down by 1. Disadvantage on Str rolls, speed reduced by 5

  
**** Red Potions
 - 1 Potion of Greater Healing: Heal 4d6+4 // Heal d6
 - 2 Potion of Fire Breathing: You can use a bonus action to exhale fire in a cone 30 feet in front of you. All creatures in the cone must make a DC 13 Dexterity saving throw, taking 4d6 fire damage on a failed save, or half as much damage on a successful one. The effect ends after you exhale the fire three times or when 1 hour has passed. / Explodes for 4d6 damage in 13 ft circle, DC 13 save for half damage.
 - 3 Potion of Fire Giant's Strength: STR Increases to 25 for one hour / increases by 2

**** Green Potion
  - 1 Potion of Ooze: Get Ooze Poisoning / same
  - Strong acid: Make DC 15 CON save. 4d6 on fail, halved on success. / 1d6 damage for 3 turns, -3AC if heavy armor
  -  

    
*** Loot
**** Scroll of Enlarge/Reduce
**** Helmet of Equine Glory
     Golden helmet. Hole on top for horns. Also golden horns right behind them, like a deer.
     - Your jump distance/height is tripled.
     - Can headbutt and gore. If minotaur-charge, target takes an extra 13 (2d8 + 4) damage instead of 9 (2d8). If not, get minotaur charge.
     - +2 to intimidation
**** In secret potion cabinet
     - 3 golden potions. Make you invulnerable to psychic effects for 6 hours.
     - 2 turquoise potions. Potion of Brilliance. +8 intelligence for an hour. -8 intelligence for eight hours.
     - 2 pink potions. Potion of Giant Strength. +8 strength for an hour. -8 strength for eight hours.
     - Magic potion recipe book. 3 pages. Write on it, it will respond with words or with a recipe.
     - Potion organization kit! Though only 12" by 5" by 5", this can magically hold 18 potion bottles.

 
    


