* Storylines
** Feyhammer Migration
In 1476, [[Marod Feyhammer]] and [[Elena Feyhammer]] were en route from Calimport to Murann, in the Amn (Calimport -> Memnon -> Velen -> Murann). They were part of a small trading contingent, with three ships. Early one morning, when they were a week away from Velen, Elena remembers how her father barged into her room, in a seeming frenzy. He tore through her drawers, looking for a brooch he himself had gifted her for her fifteenth birthday; one that would amplify certain abjuration spells. He found it, with nary an explanation, and rushed out to talk to the Captain, [[Santanos Morialdos]]. He convinced the captain to stop the ship, showing him visions of treasure far below the sea, and promising him the world.

On the deck of the 'Prima Victoria', in front of the collected crew, Marod opened a portal, and stepped through. Elena remembers the collected crewmembers worridly clutching their weapons, ready for monsters from the deep to come through; they were nervous, held together only by their faith in their captain and lust for treasure.

For three hours they stood there, getting more and more restless. Santanos was eying the portal warily, almost wishing for it to close so he could continue. And then, it happened. Marod returned, carrying a bag with a crown bejeweled with rubies, fit for any king, and gold coins, minted in a time long past. Elena remembers the backs of the coins as having a crossed sickle and trident, though the pattern on the front eludes her.

For the next hour, Santanos excitedly told the captain and the crewmembers of the place he had found -- an underwater palace, protected from the outside by powerful magic, abandoned yet still filled with treasures. He offered to take several soldiers with him -- winking and claiming that he needed more men to carry the treasures out. However, no matter how much she pleaded, he would not allow Elena to go through, and made sure she was kept away from the portal. And so, one hour later, as the sun shone at its height in the sky, he and six other men, all good combinations of brave, foolhardy, and expendable, ventured back through the portal.

They returned four hours later, all smiles, each with pockets filled with gold and jewels, each carrying a vase or samovar or some other treasure, each a walking fortune, regaling those left on the ship with stories of what they'd seen. One told of a library the size of a small village, with books going up the walls to the height of a fair-sized giant. Another told of a kitchen, with poultry that prepared itself and silverware more gem than metal. Each recollection was greater than the last.

Captain Santanos, not wanting to push his luck and run afoul of the pirates of Nelanther, decided on a single further expedition. Across all three ships, thirty good men were chosen to join Marod. Again, Elena tried to join them, and again she was denied. As the sun was setting, they ventured through the portal. All evening the remainder of the crew waited for them, and all night, and the next day, and the next night. That morning, though, the portal started swirling, belching black ichor that burned whatever it touched, and pulling in everything in its surroundings.

Most of the men evacuated the 'Prima Victoria' as she burned. Those that didn't were incinerated by the fire, ingested by the portal, or consumed by the waves. They watched as the ship sunk, and the portal collapsed on itself. They mourned their comrades, but knew that now was time to leave the area; the smoke was sure to bring on predators, and the crew was in no shape to fight them. So they continued on their journey to Velen and the Amn, richer in gold but nothing else.

One day away from Velen, the crews of the remaining ships, 'The Last Stand' and 'Heart of Iron', received a rude surprise. Strewn all over the two ships were the bodies of the thirty men who had gone into the portal. Marod was nowhere to be seen. They were unintelligible, spewing gibberish, looking miserable and confused. The taxed crew cared for their mates until the ship reached Velen, where they were dropped off on the streets. There's no room at Sea for incapable men.

Elena made it to Murann in one piece, but without her father, and much poorer.

** Lemuria Expedition
*** Negotiation
**** Desired Qualifications
- At least five years of adventuring experience.
- Must be able to handily deal with two goblins.
- Knowledge of the arcane, history, foreign languages, and other similar skills desired.
- Two professional references per applicant.

**** Insurance
Insured with Calceri Bank. 
- In the event of verified death, 1000gp goes to loved ones.
- In the event of maiming, up to 300gp paid out, to be decided in the Harpers' court.
- If Elena returns, an extra 400gp will go to the hero or their descendants.
- For every additional crew member that returns, an extra 50gp will go to the hero or their descendants. 

**** Base salary
- 100gp up front.
- 200gp or 1% of loot upon return, whichever is higher.
- Bonuses to be handed out at the discretion of the hiring party to incentivize heroism.

*** Summary
- [[Elena Feyhammer]] and [[Himo Liadon]] are collecting a group of adventurers (mercenaries) to go hunting for the lost land of Lemuria!

* Legends
** Of Lemuria
- Legends speak of an island city to the west of Faerun, in the Trackless Sea, north of Chult and East of Lantan.
- Maps from different years differ with regards to the exact location.
- The city disappeared four hundred years ago, utterly and completely.
  
* Locations
** Lantan
- Former island nation in the trackless sea
- Used to be populated by gnomes and humans
- Advanced technology
** Lemuria
** Ashenmire Palace
- Three story palace, one of the largest in the Sea Ward of Waterdeep (the wealthiest ward of the city)
- Circular, with greenery on the edges of the rectangular property.
- Palace itself is deep red, with intricately carved white columns with gold-plated bases  on the outside 
- Strategically positioned globes lit with purple fire.
- Floors can shift locations.
- Circle has a radius of about 150 feet.
*** For the Farewell Feast
- Upon entering the building, big circular open area with high ceilings.
- Lavishly decorated; painted windows (but none on the outside), frescos on the ceiling.
- Bar in the middle of the room, tables arranged around it for the guests.
- Elegantly dressed men and women (mostly women) in red and purple uniforms relax in a lounge to the side, talking to each other. They mostly stop as people come in and start walking around.
- Ashenmire is standing in the corner, wearing a white suit. As the crew comes in, he welcomes them.
- Santiano is playing music in the corner.
** Heart of Iron

* PC
** Shadow of the Towers
** Valeria Greenleaf
- 250 years old
- Merchant of Waterdeep
- Family of merchants
- Operate warehouses, caravans, stores.
- Elf Cosmetics, front
- Emerald Enclave
- 
** Therapon
- Minotaur
* NPC
** From 'Heart of Iron'
*** Ishri
- Eater of Khalul
- Will try to infiltrate mission, sabotage it, and take the treasures for Khalul
- In true form, is a tall, dark skinned woman. 
- Black eyes.
- Wears black arabic cape with a brooch that shines in the darkness holding her cape on her chest.
*** Captain Monsignore
- Captain of the 'Heart of Iron'.
- Grizzled, but french.
- In the Amnish navy for twenty years.
- Was caught smuggling several hearts of Glustrod as an on-duty captain, but was rescued from execution by a mysterious stranger.
- Used his smuggling wealth to buy a new ship and became a pirate hunter operating in Waterdeep.
*** Bruce the Beast (Willis)
- First mate
- Six feet tall human male
- Bald
- Can be freakishly strong when his ship's in danger
- Got his nickname when he singlehandedly shifted the sail on the 'Heart of Iron', turning the ship in a critical moment against 'Barborbossa'.
*** Pudge (Pudgeosopher, po-boy to his friends)
- Ship cook
- Gloriously fat
- Once fought off three pirate scum that entered the kitchen.
** From Ashenmire Palace


** From Waterdeep
*** Bayaz
- https://vignette.wikia.nocookie.net/firstlaw/images/2/2e/Bayaz-GraphicNovel.jpg/revision/latest?cb=20140307222848
- Bayaz looks maybe sixty, heavily built, with a strong face, deeply lined, and a close-cropped grey beard around his mouth. He is entirely bald, with a tanned pate.
- Goes by 'Lord Colm Ashenmire'.
- Lord of Waterdeep
- Level 15 Wizard-Sorcerer
- Patron of [[Elena Feyhammer]].
*** Yoru Sulfur
- https://vignette.wikia.nocookie.net/firstlaw/images/3/34/YoruSulfur-GraphicNovel.jpg/revision/latest?cb=20140307222306
- Male, human, 30s, southern skin color, but not so dark as to be Calmshite
- One blue eye and one green
- Nondescript dress, pleasant but forgettable, humble manner.
- [[Bayaz]]'s eater and shapeshifter.
*** Khalul
- Trapped by Bayaz in Lemuria.
- Released by [[Marod Feyhammer]].
*** Marod Feyhammer
- Male human calishite, 77
- Father of [[Elena Feyhammer]]
- Calishite merchant and later aristocrat.
- Later in life, wanted to migrate to the Amn: [[Feyhammer Migration]].
*** Elena Feyhammer
- https://img00.deviantart.net/499d/i/2013/083/d/b/melisandre_by_imperfectsoul-d5z5nac.jpg
- Wanted to be an adventurer, like those in the tales.
- Female human calishite, 46
- Level 5 Sorcerer
- Gift for divination
- Has had worsening magical dreams about her father [[Marod]] for the past 7 months. They point her southwards.
- Approached by [[Bayaz]]
- Wearing noble clothing (maybe trying a bit too hard)
*** Logen Ninefingers
- https://vignette.wikia.nocookie.net/firstlaw/images/1/19/Logen_ninefingers_wip_y_icedwingsart-d8guxcx.jpg/revision/latest?cb=20150512083852
- Level 7 human Barbarian
- Elena's bodyguard
- Six foot Barbarian, wielding a massive claymore.
- Armored in leather.
- Terse
- Very heavily scarred face and arms.
- From the far North -- fled into exiled after briefly achieving hegemony amoung the tribesmen.
- When raging, can become the Bloody-Nine
- Hired by [[Bayaz]] to accompany [[Elena Feyhammer]].
*** Renault Monet
- Halfling Cartographer
- Brought in to resolve discrepancies in the maps by [[Elena Feyhammer]].

*** Reginald Truthseeker
- Bald human male monk
- Legal Witness of Waterdeep
- Will try to force honesty from both Elena and the PCs during negotiations.
- Magical quill will be taking notes during negotiations. Crossing out deletes things.
** From Calimport
*** Santanos Morialdos
- Captain of the Prima Victoria, the ship from which [[Marod Feyhammer]] had first found Lemuria.
- Elderly, wrinkled, with a wry sense of humor, a scar across his right eye, and a peg leg.
* Artifacts
** Glustrod's Heart
- Named after the first Eater, Glustrod
- Gives the eater of the heart a taste for human flesh.
* Sessions
** Session 0
*** Plan
Finish their character sheets.
Introduce their characters to each other (the players)
Familiarize them with the world and have them ask questions and answer some, like what town are their characters from.
Ask them what they want to get out of the game/campaign
Brainstorm relationships and connects
What is something they (the player) wants to accomplish
What is something their character wants to accomplish
Go over any home rules or just the rules (maybe do a simple fight or something here, non-cannon)
Job Interview
*** Things you know
**** Spread of a plague in the South has 
*** Summary
** Predictions
*** If the 

* Stuff
** Crown of Vesuvius

